### ISSUE TITLE
Flight buttons are fully inverted

### ISSUE THREAD

**Issue by Nikitonz** [ShimmyMySherbet/ShimmysAdminTools#20] opened 2023-03-07 16:33 UTC
For example, writting /afly gives you flight ability, ok
but , when pressing W - players goes back, as when pressed S. Same for A,D

**Comment by Nikitonz** [comment] 2023-03-07 16:34
it's a bug, or what?

**Comment by ShimmyMySherbet** [comment] 2023-03-29 00:24
Yes, that sounds like a bug and is something I need to look into. However, I'm not sure when I would be able to due to my limited time for Unturned-related projects.

**Comment by ShimmyMySherbet** [comment] 2023-03-29 05:49
Looks like this was caused by the change to Unturned's player input, and was an issue with changing flight speed via the hotkeys. This has since been fixed in the latest release.
If you still continue to experience issues after the update, feel free to re-open the issue.

**Closed by ShimmyMySherbet** 2023-03-29 05:49 UTC
Labels: bug
