### ISSUE TITLE
Issues since Unturned update 3.23.4.0 (24-03-2023)

### ISSUE THREAD

**Issue by robbertgroen** [ShimmyMySherbet/ShimmysAdminTools#21] opened 2023-03-26 11:48 UTC
I'm experiencing issues with the functionality of the plugin since the Unturned update 3.23.4.0 (the plugin worked fine up until the mentioned update), examples:

- pointtool jump not working
- pointtool destroy not working
- pointtool utility not working

I've not tested every command.

/checkowner, /firework and /boom work like before.

Tested on 4 different (Linux based) dedicated servers. I do not see any error messages on the server(s) console(s).

Does anyone have a solution?

Thanks in advance for any helpful suggestion!

p.s. I use the latest version of the plugin v.1.7, the file property details state file version 1.6.0.0 and product version 1.6.0.0 (downloaded a fresh copy twice to double check, is this me misunderstanding something or....)

**Comment by ItsRodrigoAl** [comment] 2023-03-27 15:53
same here

**Comment by yanisssch** [comment] 2023-03-27 18:36
same too

**Comment by asineth0** [comment] 2023-03-29 00:14
Horizon: Life RP doesn't have this issue. https://discord.gg/horizonliferp

**Comment by yanisssch** [comment] 2023-03-29 00:17
> Horizon: Life RP doesn't have this issue. We built our own /salvage and /pt commands. https://discord.gg/horizonliferp

If you built your own pt commands u don't need to wait an update from shimmy

**Comment by ShimmyMySherbet** [comment] 2023-03-29 00:21
I'll need to look into this, though since I still have a lot on my plate I have very limited time for Unturned-related issues right now.
Also, @asineth0 please do not advertise your server here. This is to discuss issues or ideas for the plugin, not to promote your Unturned server.

**Comment by ShimmyMySherbet** [comment] 2023-03-29 03:01
I believe I have found the cause of this issue. For whatever reason, it looks like while the player input for Primary/Secondary attacks (M1 and M2) are still present, they are no longer active.

The client just no longer sends that info to the server from what it seems, and because point tools were using player input instead of gestures so it could be used faster than punching allowed, and also in safe zones.

I'll need to look into it further

**Comment by ShimmyMySherbet** [comment] 2023-03-29 05:48
Eventually found a workaround for this issue, and it has been fixed in the latest release v1.7.2.
Also thanks to SeniorS for catching me up on the changes to Unturned's code during my absence.

If you continue to experience any issues, feel free to re-open this issue.

**Closed by ShimmyMySherbet** 2023-03-29 05:48 UTC
Labels: bug
